### ISSUE TITLE
Using Acado with ROS Kinetic

### ISSUE THREAD

**Issue by DianeBury** [clearpath-gbp/acado-release#1]
Hi,
I am developing an optimal control for the teleoperation of a drone in **ROS Kinetic** and I was planning on using Acado for it. But latest version is Indigo and the sources are not catkinized, so I can't clone the repo and try and built it like it is, and I'm not familiar with how to wrap an external library in ROS. Is there any plan of updating Acado for Kinetic ?

**Comment by mikepurvis** [comment]
Hi Diane,

It is unlikely we'll be updating this release repo in the future. However, note that you can build Acado (or any plain CMake package) as part of a catkin_tools (or catkin_make_isolated) workspace, as long as you supply a correct `package.xml` file. Simply clone the upstream source as you would for any other ROS package, and then copy in the file— you're welcome to use the one from this repo:

https://github.com/clearpath-gbp/acado-release/blob/release/indigo/acado/package.xml

**Comment by DianeBury** [comment]
Thanks.
I finally installed it directly and linked it to the project without building it with catkin, works fine.
